# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

branches:
  only:
    - master
    - develop
    - /feature\/.*/

env:
  matrix:
    - DEFAULT_JOB=true

matrix:

  exclude:
    - env: DEFAULT_JOB=true

  include:
    - os: linux
      dist: trusty
      compiler: g++
      env: COMMENT=trusty-g++

    - os: linux
      dist: trusty
      compiler: clang++
      env: COMMENT=trusty-clang++

    - os: linux
      dist: xenial
      compiler: g++
      env: COMMENT=xenial-g++

    - os: linux
      dist: xenial
      compiler: clang++
      env: COMMENT=xenial-clang++

    - os: osx
      compiler: clang++
      env: COMMENT=macos-clang++

script:
  - mkdir __build__
  - cd __build__
  - cmake ..
  - cmake --build . --target check

notifications:
  email:
    on_success: always
