# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install: off

build: off

test_script:
  - mkdir __build__
  - cd __build__
  - cmake ..
  - cmake --build . --target check
